### ISSUE TITLE
Problems running the demo

### ISSUE THREAD

**Issue by danielres** [lynndylanhurley/redux-auth-demo#2]
Thanks for putting this all together !

When running `npm run start`, i get:

```
> redux-auth-demo@0.0.1-alpha1 start /home/apps/expresto/expresto-2016/frontend/redux-auth-demo
> node --harmony ./babel.server

/home/apps/expresto/expresto-2016/frontend/redux-auth-demo/node_modules/redux-auth/bootstrap-theme.js:2
ype:"submit",className:"pull-right",icon:this.props.icon,disabled:n,className:
                                                                    ^^^^^^^^^
SyntaxError: Duplicate data property in object literal not allowed in strict mode
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Module._extensions..js (module.js:478:10)
    at Object.require.extensions.(anonymous function) [as .js] (/home/apps/expresto/expresto-2016/frontend/redux-auth-demo/node_modules/babel-register/lib/node.js:138:7)
    at Module.load (module.js:355:32)
    at Module._load (module.js:310:12)
    at Function.module._load (/home/apps/expresto/expresto-2016/frontend/redux-auth-demo/node_modules/piping/lib/launcher.js:32:16)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/apps/expresto/expresto-2016/frontend/redux-auth-demo/src/views/partials/RequestTestButton.js:17:23)
```

`npm run watch` outputs:

```
[1] /home/apps/expresto/expresto-2016/frontend/redux-auth-demo/node_modules/redux-auth/bootstrap-theme.js:2
[1] ype:"submit",className:"pull-right",icon:this.props.icon,disabled:n,className:
[1]                                                                     ^^^^^^^^^
[1] SyntaxError: Duplicate data property in object literal not allowed in strict mode
[1]     at exports.runInThisContext (vm.js:73:16)
[1]     at Module._compile (module.js:443:25)
[1]     at Module._extensions..js (module.js:478:10)
[1]     at Object.require.extensions.(anonymous function) [as .js] (/home/apps/expresto/expresto-2016/frontend/redux-auth-demo/node_modules/babel-register/lib/node.js:138:7)
[1]     at Module.load (module.js:355:32)
[1]     at Module._load (module.js:310:12)
[1]     at Function.module._load (/home/apps/expresto/expresto-2016/frontend/redux-auth-demo/node_modules/piping/lib/launcher.js:32:16)
[1]     at Module.require (module.js:365:17)
[1]     at require (module.js:384:17)
[1]     at Object.<anonymous> (/home/apps/expresto/expresto-2016/frontend/redux-auth-demo/src/views/partials/RequestTestButton.js:17:23)
[0] Hash: 2d55e55fbcd1a84e7713
[0] Version: webpack 1.12.9
[0] Time: 17143ms
[0]                                  Asset     Size  Chunks             Chunk Names
[0]   f4769f9bdb7466be65088239c12046d1.eot  20.1 kB          [emitted]  
[0] 448c34a56d699c29117adc64c43affeb.woff2    18 kB          [emitted]  
[0]  fa2772327f55d8198301fdb8bcfc8158.woff  23.4 kB          [emitted]  
[0]   e18bbf611f2a2e43afc071aa2f4e1512.ttf  45.4 kB          [emitted]  
[0]   89889688147bd7575d6327160d64e760.svg   109 kB          [emitted]  
[0]                              client.js  15.3 MB       0  [emitted]  main
[0]    [0] multi main 52 bytes {0} [built]
[0]     + 1960 hidden modules
[0] 
[0] WARNING in ./~/encoding/lib/encoding.js
[0] Critical dependencies:
[0] 9:12-34 the request of a dependency is an expression
[0]  @ ./~/encoding/lib/encoding.js 9:12-34
[0] http://localhost:8080/
[0] webpack result is served from http://localhost:8080/dist/
[0] content is served from ./static
```

And if I visit http://localhost:8080/, I just see the content of the 'static/' dir.

Any ideas on how to run the demo ?

Environment:
- Ubuntu 15.04
- npm 3.5.2
- node v0.12.7

Thank you

**Comment by lynndylanhurley** [comment]
Hi @danielres - I'll look into this today.

**Comment by lynndylanhurley** [comment]
I can't reproduce this issue on OS X. I've been testing against node `4.2.1` and `5.1.0`. I'll try against `0.12.7` and see if that generates the error. If that fails, I'll install an ubuntu vm and test there.

**Comment by danielres** [comment]
Amazing, thanks !

**Comment by fozcodes** [comment]
@danielres not sure if you ever sorted this out, but I had a different set of errors (missing semicolons). Once I cleared them all out, the server started correctly and served the app just like the demo. Looks like your errors are related to strict mode - if you can fix them, things should go back to normal.

Hope that helps.

**Comment by lynndylanhurley** [comment]
Please try again with the latest release.
